ACTION_IF MOD_IS_INSTALLED ~WarslingSniperKit.TP2~ ~0~ THEN BEGIN

	OUTER_SET help = RESOLVE_STR_REF(@3)
	OUTER_SPRINT "WarslingSniperKit_A0WS" "A0WS_0"

END ELSE ACTION_IF MOD_IS_INSTALLED ~WarslingSniperKit.TP2~ ~1~
					AND NOT MOD_IS_INSTALLED ~WarslingSniperKit.TP2~ ~3~ THEN BEGIN

	OUTER_SET help = RESOLVE_STR_REF(@31)
	OUTER_SPRINT "WarslingSniperKit_A0WS" "A0WS_1"

END ELSE ACTION_IF MOD_IS_INSTALLED ~WarslingSniperKit.TP2~ ~2~
					AND NOT MOD_IS_INSTALLED ~WarslingSniperKit.TP2~ ~4~ THEN BEGIN

	OUTER_SET help = RESOLVE_STR_REF(@32)
	OUTER_SPRINT "WarslingSniperKit_A0WS" "A0WS_2"

END ELSE ACTION_IF MOD_IS_INSTALLED ~WarslingSniperKit.TP2~ ~4~ THEN BEGIN

	OUTER_SET help = RESOLVE_STR_REF(@33)
	OUTER_SPRINT "WarslingSniperKit_A0WS" "A0WS_3"

END ELSE ACTION_IF MOD_IS_INSTALLED ~WarslingSniperKit.TP2~ ~3~ THEN BEGIN

	OUTER_SET help = RESOLVE_STR_REF(@34)
	OUTER_SPRINT "WarslingSniperKit_A0WS" "A0WS_4"

END

INCLUDE ~WarslingSniperKit/lib/a7#add_kit_ex.tpa~

LAF ADD_KIT_EX
	INT_VAR
	kit_class // OUTER_SET
	lower     = RESOLVE_STR_REF(@1) /*~warsling sniper~*/
	mixed     = RESOLVE_STR_REF(@2) /*~Warsling Sniper~*/
	help      /* = RESOLVE_STR_REF(@3) ~WARSLING SNIPER: The sling is a difficult weapon to master, but in the hands of a warsling sniper it becomes a precise tool of war. Although slings are commonly associated with and used by the hin, experts of the weapon may indeed come from any race.

	Advantages:
	-  +1 bonus to hit and damage with missile weapons at first level and every 4 levels afterward
	-  At 10th level he gains the Improved Ricochet passive ability which allows all fired missiles to bounce off their primary target and hit one additional nearby foe

	Disadvantages:
	-  May not specialize in any weapon other than the sling
	-  May not wear armor greater than studded leather
	-  Hit Die: d8~*/
	STR_VAR
	kit_name
	unusable  = ~0x0000C000~
	hpclass = ~HPMONK~
	//  briefdesc = 31252
	//  biography = 15888
	clascolr = ~28 93 91 91 93~
	clasweap  = ~1           1           1           1           1           1           1           1~
	weapprof  = ~1 1 1 1 1 1 1 5 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 5 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	abclasrq  = ~9       0       0       0       0       0~
	abclsmod  = ~0       0       0       0       0       0~
	abdcdsrq  = ~17      0       0       0       0       0~
	abdcscrq  = ~15      0       0       0       0       0~
	alignmnt  = ~1       1       1       1       1       1       1       1       1~
	dualclas  = ~0       1       1       1       1       0~
	clab_path = EVAL ~%MOD_FOLDER%/2da/%WarslingSniperKit_A0WS%/%kit_name%.2da~
	base_class
	kittable
	luabbr
	stweap    = ~LEAT14 * * BAG28 RING06 RING05,10 * BOOT02 AMUL19 BRAC16 BELT06 BULL03,40 BULL03,40 BULL03,40 POTN52,5 POTN04,2 POTN14,5 DAGG12 SW1H28 SLNG05~
	RET
	kit_id
END
